"""
Me: Middleware allows us to add code before and after a request is executed. Why do we need this? For example, to mess with received headers, or add parameters to response headers, etc.

A "middleware" is a function that works with every request before it is processed by any specific path operation. And also with every response before returning it.

    -   It takes each request that comes to your application.
    -   It can then do something to that request or run any needed code.
    -   Then it passes the request to be processed by the rest of the application (by some path operation).
    -   It then takes the response generated by the application (by some path operation).
    -   It can do something to that response or run any needed code.
Then it returns the response.
"""


