/**
 * A subtle difference between build all and rebuild all options in the build menu is that build all only
 * creates the projects that need to be rebuilt (possibly because there's been a change to them.) Often,
 * when we change the .pro file or do some other changes that affect the dependency (mostly through this
 * file,) we need to rebuild.
 * 
 * However, rebuild all cleans every build, and rebuilds them.
 * 
 * By the way, don't be afraid to click on the build bottom below on the left, and then build the project(s)
 * you want directly from there.
 * 
 * You can also clean your project (remove all object files and other autogenerated products) by selecting 
 * Clean All.
 * 
 * The publish button allows us to publish our apps on repositories (like ubuntu repos for example.)
 */